### ISSUE TITLE
Voraussetzungen-Einkauf.md

### ISSUE THREAD

**Issue by REKLOV73** [fiskaltrust/productdescription-de-doc#111]
Bitte um Ergänzung, wie man die Rolle erhält und auch wieder Kündigen kann. Bitte auch den Prozess beschreiben, wie man ein Kreditlimit bekommt bzw. erweitern kann.

https://github.com/fiskaltrust/productdescription-de-doc/blob/master/for-posdealers/02-pre-sales/voraussetzungen-einkauf.md

**Comment by MarkusEGruber** [comment]
Hi,
die Rollen können im Portal durch Zeichnen des zugehörigen Vertrags erworden werden. Diese Verträge können auch wieder gekündigt werden. Bezüglich des Kreditlimits, wenden Sie sich bitte an sales@fiskaltrust.de

Der Einkauf wird durch die PosDealer durchgeführt.
