### ISSUE TITLE
Frage zu Epson TSE-Epson-Interoperabilit%C3%A4t.md

### ISSUE THREAD

**Issue by AxelKutschera** [fiskaltrust/productdescription-de-doc#124]
https://github.com/fiskaltrust/productdescription-de-doc/blob/master/product-service-description/compliance-as-a-service/features/TSE-Epson-Interoperabilit%C3%A4t.md
1. Woher bekommt man die Host-URL sowie den Port? Ist das immer gleich?
![image](https://user-images.githubusercontent.com/16694255/97094845-2eeb3900-1659-11eb-9242-5f21a8145094.png)
2. Ist diese Info für PosCreator auch in EN relevant?

**Comment by aedler-ft** [comment]
steht in der Doku: "Host: DNS oder IP Addresse des Epson Servers, Epson Printers oder lokalen Webservices"
für eine englische Doku fehlen uns leider die Kapazitäten.
