### ISSUE TITLE
SQLStorage

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#35]
product-service-description/compliance-as-a-service/features/SQLite-Storage.md

Dort ist beschrieben, dass die Konfigurationsdaten in der SQLite-Datenbank gespeichert werden.
Ist dies in DE unterschiedlich zu AT & FR.

**Comment by aedler-ft** [comment]
Kommt denke ich von Tom; dacsteht auch dass dieses Feature ab MW 1.3.0 verfügbar ist, diese Version ist in AT und FR noch nicht verfügbar, daher erscheint es mir plausibel.
