### ISSUE TITLE
Technische Information

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#37]
In einigen Dateien sind Konfigurationsparameter bzw. Details zur Implementierung aufgeführt.

Damit haben wir in reiner Beschreibung technische Informationen, die besser in der technischen Dokumentation (Middleware API, interface Doc) aufgehoben wären. Mit dieser Aufteilung wird es für den PosCreator schwierig die Informationen "auf einen Blick" zu erhalten. Falls wir die Information an beiden Orten haben, ist die Wartung der beiden Quellen sehr aufwändig.

**Comment by aedler-ft** [comment]
da hast du voillkommen recht. wir werden es ändern.

**Comment by aedler-ft** [comment]
wir haben das issue als Anlass genommen die Ziele und Inhalte der einzelnen Repos für unsere User nachvollziehbar zu definieren - siehe z.b. https://github.com/fiskaltrust/productdescription-de-doc#weitere-öffentliche-fiskaltrust-repositories

@TSchmiedlechner @magdignomad demnach passen Konfigurationsparameter für TSE am besten in dieses Repo.
