### ISSUE TITLE
Queue - POS-System

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#38]
product-service-description/compliance-as-a-service/features/Queue-Abstraktion.md

Muss wirklich für jedes POS-System eine Queue vorliegen (DE spezifisch?).
In AT/FR kann eine SignatureCloud-Lösung eine Queue für mehrere POS-Systeme bereitstellen.

**Comment by aedler-ft** [comment]
ja, weil für FA Meldung muss TSE-und Kassenseriennummer gemeldet warden. Jede Queue = Kassenseriennummer (CashboxIdentifikation)

**Comment by AxelKutschera** [comment]
Ich würde es so formulieren: "In Deutschland muss jeder PosOperator für jedes PosSystem und jeden Standort (Outlet) mindestens eine Queue betreiben."

- "Pos-System" o.a. sollte immer als "PosSystem" oder "KassenSystem" geschrieben werden. Das ist die Bezeichnung im ft.Portal https://portal-sandbox.fiskaltrust.de/POSSystem
- Dazu passend immer die "ftPosSystemId" https://docs.fiskaltrust.cloud/doc/interface-doc/doc/general/data-structures/data-structures.html

**Comment by AxelKutschera** [comment]
Begriffe: 
- Ich würde immer "betreiben" anstelle zB "laufen lassen" usw. verwenden.

- Der Begriff "PosSystem" wäre im https://docs.fiskaltrust.cloud/doc/interface-doc/doc/general/terminology/terminology.html zu beschreiben. 
- ebenso "SCU"
- ebenso "Outlet"

- Begriff "fiskaltrust.SecurityMechanismus" wurde definiert als --> "fiskaltrust.SecurityMechanism": https://docs.fiskaltrust.cloud/doc/interface-doc/doc/general/terminology/terminology.html

**Comment by AxelKutschera** [comment]
Zur Kassenseriennummer:
Eine CashBox kann (nach meiner Info) in DE mehrere Queues enthalten. 
Demnach müsste die Kassenseriennummer der Queue entsprechen und nicht der CashBox? (Das wurde schon öfter diskutiert.)

**Comment by magdignomad** [comment]
Und im Rollout Scenario ist aber sogar ein Bild mit mehreren Terminals auf eine Queue: productdescription-de-doc/blob/posdealer-architecture/for-posdealers/03-sales/rollout-scenarios.md

**Comment by AxelKutschera** [comment]
Ich sehe diese Aufbau:
-	Jedes PosSystem muss einer eigenen ft.Queue zugeordnet sein
-	Ein PosSystem mehrere Terminals (Eingabestationen) haben kann
-	Jedes Terminal kann die Daten an die ft.Queue senden

Jede ft.Queue stellt rechtlich eine eigene Kasse dar und ist daher dem Finanzamt zu melden.

**Comment by aedler-ft** [comment]
updates in Gloassar, Queue Abstraktion, Rollout-Szenarien basierend auf die obigen Feedbacks
