### ISSUE TITLE
Hashing & Unveränderlichbarkeit

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#39]
product-service-description/revisionssichere-daten-as-a-service/README.md

> ... die Vollständigkeit kann durch Nachverfolgung der Kassenbeleg-Hash-Kette überprüft werden. Dies bedeutet, dass alle Originaldatensätze erhalten bleiben und unveränderlich sind. Der Schutz vor...

Nur der WORM-Speicher stellt sicher, dass keine Daten verändert werden. Eine Hash-Kette stellt keine Unveränderlichbarkeit sicher, sondern zeigt die Änderungen in der Kette auf. Jedoch nicht genau die Veränderung, sondern nur den Datensatz der verändert wurde.

**Comment by aedler-ft** [comment]
werden es besser formuieren
