### ISSUE TITLE
AKO - automatischer Datenupload

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#40]
productdescription-de-doc/product-service-description/revisionssichere-daten-as-a-service/produkte/4445-10020-Audicon-Kassenarchiv-Online.md

Es werden anscheinend keine Daten beim automatischen Datenupload übertragen. Dann kann dieser Abschnitt entfernt werden?

**Comment by aedler-ft** [comment]
Produkt ist als "in Entwickung" gekennzeichnet. Die Doku wurde vorgezogen und stellt den aktuellen Stand dar, wobei wir diesen jetzt nicht tagesaktuell halten werden
