### ISSUE TITLE
fiskaltrust.Leistungsbeschreibung

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#41]
> Die fiskaltrust-Middleware verarbeitet einige der wichtigsten Datenfelder auf dem Beleg. Die Belegnummer als eindeutige Identifikation eines von der Registrierkasse übermittelten Beleges wird von der fiskaltrust-Middleware erstellt, um sicherzustellen, dass jeder Beleg von ihr verarbeitet wird.

- Was sind die wichtigsten Datenfelder? Dieser Teil impliziert, dass nicht alle Daten verarbeitet werden.
- Stellt die Belegnummer wirklich die Verarbeitung durch die fiskaltrust.Middleware sicher? Ist nicht die Belegnummer das eindeutige Zeichen, dass der Beleg von der fiskaltrust.Middleware verarbeitet wurde?

> Um Unveränderlichkeit zu gewährleisten, wird ein weiterer Hash-Wert generiert, der sich auf den gesamten Anforderungs-Antwort-Zyklus bezieht, einschließlich der Identifizierung des Zyklus, des Betriebszeitpunkts, der vom Menschen lesbaren Belegnummer und der Hash-Werte von Anforderung, Antwort und vorherigem Empfang, der so genannte Belegs-Hash-Wert. Diese Verkettung des Empfangs-Hash-Werts bietet Unveränderlichkeit und bietet die Möglichkeit, alle Änderungen und auch das Löschen bei jeder vom Possystem bereitgestellten Aktion zu erkennen.

- Hashing stellt doch keine Unveränderlichbarkeit sicher?
- alle Änderungen... impliziert, dass die genau Veränderung erkannt wird. Hashing zeigt jedoch nur, dass der Datensatz verändert wurde.
- das Löschen... impliziert, dass genau erkannt wird wie viel gelöscht wurde. Eine Unterbrechung der Kette zeigt aber nur, dass ein/mehrere Wert(e) entfernt wurden.

**Comment by aedler-ft** [comment]
Text wird allgemenin überarbeitet
