### ISSUE TITLE
Dauer der Datenspeicherung

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#42]
In den Dokumenten wird von verschiedenen Zeiträumen gesprochen:

- bis zu 10 Jahre
- 10 Jahre
- über 10 Jahre

Diese Werte sollten angeglichen werden, da Sie ein Produktmerkmal sind!

**Comment by aedler-ft** [comment]
-> werden "über 10 Jahre" verwenden

**Comment by AxelKutschera** [comment]
Geht es um die Aufbewahrung für steuerliche Zwecke?
Dann sind es 6 oder 10 Jahre jedoch beginnt die Frist "mit dem Schluss des Kalenderjahrs, in dem die letzte Eintragung in das Buch gemacht, [...] die Aufzeichnung vorgenommen worden ist oder die sonstigen Unterlagen entstanden sind."
Das sind im Extremfall daher 12 Jahre.

https://www.gesetze-im-internet.de/ao_1977/__147.html
