### ISSUE TITLE
Endverbraucher-Preisliste

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/productdescription-de-doc#45]
productdescription-de-doc/tree/master/for-posoperators

Ich denke wir haben keine Endverbraucher (=Konsument, wird nach der ) sondern PosOperatoren. Dieses Wort im deutschen Handel eigentlich nur im Lebensmittelbereich verwendet, da hier ein Produkt verbraucht wird.

**Comment by aedler-ft** [comment]
wir werden Endkunden verwenden, steht so im Entgeltblatt selbst

**Comment by AxelKutschera** [comment]
Ich würde "PosOperator" oder "KassenBetreiber" verwenden und es hier beschreiben: https://docs.fiskaltrust.cloud/doc/interface-doc/doc/general/terminology/terminology.html

**Comment by aedler-ft** [comment]
Guter Input @AxelKutschera bezügl. der Definition KassenBetreiber etc; ich werde die Definition im Glossar der Produktdokumentation aufnehmen!
