### ISSUE TITLE
PosSystem definition

### ISSUE THREAD

**Issue by steininger** [fiskaltrust/productdescription-de-doc#58]
Ist die Kassensoftware.
Ein Kassensystem ist eine Instanz der Kassensoftware in Verbindung mit Hardware und Pereferiegeräten.
Details dazu auch in den Begriffsdefinitionen der Verträge:
https://github.com/fiskaltrust/legal/blob/master/company-de/partner-poscreator-closing.html
https://github.com/fiskaltrust/legal/blob/master/company-de/partner-posdealer-closing.html

**Comment by AxelKutschera** [comment]
Als Ergänzung: Das "elektronische oder computergestützte Kassensysteme oder Registrierkassen" ist hier in Punkt 1.2 
beschrieben:
https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Weitere_Steuerthemen/Abgabenordnung/AO-Anwendungserlass/2019-06-17-einfuehrung-paragraf-146a-AO-anwendungserlass-zu-paragraf-146a-AO.pdf?__blob=publicationFile&v=1
