### ISSUE TITLE
Input on how to make getting-started easier.

### ISSUE THREAD

**Issue by AxelKutschera** [fiskaltrust/productdescription-de-doc#73]
This "old" workflow has a complete numbering of the individual points around the most important process to create a CashBox in the test environment. (DE: https://fiskaltrust.de/fiskaltrust/faq/faq-partner/ oder EN: https://fiskaltrust.de/en/faq-partner/)
Damit könnte das getting-started erleichtert werden: https://github.com/fiskaltrust/productdescription-de-doc/blob/master/for-poscreators/getting-started.md 

In der Sandbox https://portal-sandbox.fiskaltrust.de aktuell bitte folgendes ausführen:
A. Erstellung einer Cashbox mit fiskaly Online TSE
1. Im Menü ihre Firma/Übersicht auswählen und sicherstellen, dass die Rolle als Kassen Händler auch ausgewählt ist.
2. Im Menü ihre Firma/Stammdaten kontrollieren, dass eine „Stadt“ eingetragen ist.
3. Im Menü Shop/Produkte zuerst oben bei Standort-Id von „KEINE VERKAUFSSTELLE“ auf einen bestehenden Standort ändern, danach rechts oben bei der Suche die Produktnummer 4445-20100 eingeben.
4. Die „Fiskaly cloud TSE“ in den Warenkorb legen und den Checkout über den Warekorb machen. Die Bestellung (kostenlos) „Verbindlich Bestellen“
5. Nach etwa einer Minute sollte bei Konfiguration/TSE- Signaturerstellungs Einheit eine „Fiskaly-Cloud TSE – Outlet: (outletname) (n)“ angelegt worden sein.
6. In dieser Zeile auf Konfiguration klicken und bei Url auf gRPC klicken, speichern und schließen
7. Im Menü Konfiguration/Queue +neu anlegen, eine beliebige Beschreibung auswählen, bei CashboxIdentification etwa fiskaltrust100 eintragen (normalerweise die letzte Package Version belassen), speichern. (Die CashboxIdentification darf kein Leerzeichen “ “ und keinen Unterstrich „_“ enthalten)
8. Bei url folgende Varianten angeben, um alle Möglichkeiten einzurichten (jeweils in einer Zeile):
* rest://localhost:1500/ftrest  (für REST Endpunkt  localhost:1500/ftrest/json/v1/sign etwa)
* grpc://localhost:1400(für GRPC)
* http://localhost:1200/fiskaltrust (für WCF, SOAP)
Alternativ kann auch durch klicken auf den entsprechenden Button in jeweils einer Zeile der Eintrag vorgenommen und übernommen werden.
Danach „Speichern und Schließen“
9. Im Menü Konfiguration/Queue bei der verwendeten Queue „Gebrauchte deutsche Signaturerstellungseinheit“ (vierter Button von rechts) anwählen, dann die erstellte Fiskaly Signaturerstellungseinheit auswählen, speichern.
10. Im Menü Konfiguration/Cashbox auf „+Hinzufügen“ klicken und eine beliebige Beschreibung, Feld IP-Adresse kann leer bleiben, Speichern
11. Im Menü Konfiguration/Cashbox in der Zeile der neuen Cashbox auf Bearbeiten per Drag and Drop gehen, Die erstellte Queue und die erstellte SCU von rechts nach links schieben per Drag and Drop, speichern
12. Im Menü Konfiguration/Cashbox in der Zeile der neuen Cashbox rebuild configuration klicken, Dann den launcher herunterladen und entpacken,
13. test.cmd rechtsklick, als Administrator ausführen.
 
B. Erstellung einer Cashbox mit Swissbit USB TSE
1. Im Portal Konfiguration -> TSE / Signatur-Erstellungs-Einheit
+Erstellen klicken
2. Beschreibung beliebig eingeben, Package Name fiskaltrust.Middleware.SCU.DE.Swissbit, letzte Version belassen normalerweise
Speichern klicken
3. Gerätepfad, den Laufwerksbuchstaben der Swissbit TSE eingeben (z.B.: „E:“ ohne Anführungszeichen)
4. Auf gRPC klicken, Speichern und schließen
-> bei Punkt 7 oben weitermachen

**Comment by aedler-ft** [comment]
https://fiskaltrust.de/fiskaltrust/faq/faq-partner/ is deprecated; and I can't find a product with the number 4445-20100 in the shop. are you sure this how-to-guide is correct?

**Comment by AxelKutschera** [comment]
Replaced by https://docs.fiskaltrust.cloud/doc/productdescription-de-doc/for-poscreators/getting-started.html
