### ISSUE TITLE
Postman - Initial operation receipt - Error 415

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/productdescription-de-doc#78]
Bekomme beim Absetzen des Requests via Postman folgende Fehlermeldung:
Cannot process the message because the content type 'application/json' was not the expected type 'text/xml; charset=utf8'

**Comment by TSchmiedlechner** [comment]
Hallo,
das könnte mehrere Gründe haben. Verwenden Sie möglicherweise einen SOAP-HTTP-Endpunkt mit der Postman-Collection? Diese ist nämlich nur für REST-Endpunkte vorgesehen.

Falls das nicht das Problem ist: welche Version der Middleware haben Sie im einsatz?

**Comment by DS-DEV678** [comment]
Hallo,

ja verwende SOAP-http Endpunkt.
Reicht es wenn ich in der MW Config zu der SOAP auch die REST Endpunkt hinzufüge.
Ist die Reihenfolge relevant?

Verwende die Version 1.3.4.0

LG

Von: Tom Schmiedlechner <notifications@github.com>
Gesendet: Dienstag, 18. August 2020 08:46
An: fiskaltrust/productdescription-de-doc <productdescription-de-doc@noreply.github.com>
Cc: Daniel Sumak <daniel.sumak@bizsoft.biz>; Author <author@noreply.github.com>
Betreff: Re: [fiskaltrust/productdescription-de-doc] Postman - Initial operation receipt - Error 415 (#78)


Hallo,
das könnte mehrere Gründe haben. Verwenden Sie möglicherweise einen SOAP-HTTP-Endpunkt mit der Postman-Collection? Diese ist nämlich nur für REST-Endpunkte vorgesehen.

Falls das nicht das Problem ist: welche Version der Middleware haben Sie im einsatz?

**Comment by TSchmiedlechner** [comment]
Hallo,
richtig, es sollte reichen den REST-Endpunkt hinzuzufügen. Die Reihenfolge ist nicht relevant.

**Comment by DS-DEV678** [comment]
Super danke

Von: Tom Schmiedlechner <notifications@github.com>
Gesendet: Dienstag, 18. August 2020 09:05
An: fiskaltrust/productdescription-de-doc <productdescription-de-doc@noreply.github.com>
Cc: Daniel Sumak <daniel.sumak@bizsoft.biz>; Author <author@noreply.github.com>
Betreff: Re: [fiskaltrust/productdescription-de-doc] Postman - Initial operation receipt - Error 415 (#78)


Hallo,
richtig, es sollte reichen den REST-Endpunkt hinzuzufügen. Die Reihenfolge ist nicht relevant.

**Comment by TSchmiedlechner** [comment]
Gerne!

_Quick summary for non-English speakers: if you receive this error, you are most likely trying to access a SOAP HTTP endpoint via this Postman collection, which only supports REST. Please add a REST endpoint to the Middleware and use that one._
